apiVersion: v1
kind: Secret
metadata:
  name: chessverse-backend-secret
  namespace: chessverse
type: Opaque
stringData:
  db-url: jdbc:postgresql://replace-with-rds-endpoint:5432/chessverse
  db-username: chessverse
  db-password: replace-me

