apiVersion: v1
kind: Secret
metadata:
  name: chessverse-backend-secret
  namespace: chessverse
type: Opaque
stringData:
  db-url: jdbc:postgresql://replace-with-rds-endpoint:5432/chessverse
  db-username: chessverse
  db-password: replace-me
  mail-username: replace-with-smtp-user
  mail-password: replace-with-smtp-secret
  mail-from: no-reply@replace-with-your-domain.com
  allowed-origin-patterns: https://replace-with-your-web-domain.com
