import '../app_language.dart';

/// Compact, bundled notification copy. Tournament names remain unchanged while
/// all surrounding reminder text follows the selected app language.
const Map<String, List<String>> _copy = <String, List<String>>{
  'en': [
    'starts tomorrow',
    'starts in 1 hour',
    'starts in 10 minutes',
    'Review your preparation and return for your pairing.',
    'Your registered tournament is almost ready.',
    'Open the tournament bracket and get ready to play.',
  ],
  'te': [
    'రేపు ప్రారంభమవుతుంది',
    '1 గంటలో ప్రారంభమవుతుంది',
    '10 నిమిషాల్లో ప్రారంభమవుతుంది',
    'మీ సన్నద్ధతను సమీక్షించి మీ జోడీ కోసం తిరిగి రండి.',
    'మీరు నమోదు చేసుకున్న టోర్నమెంట్ దాదాపు సిద్ధంగా ఉంది.',
    'టోర్నమెంట్ బ్రాకెట్‌ను తెరిచి ఆడటానికి సిద్ధంగా ఉండండి.',
  ],
  'hi': [
    'कल शुरू होगा',
    '1 घंटे में शुरू होगा',
    '10 मिनट में शुरू होगा',
    'अपनी तैयारी की समीक्षा करें और अपनी जोड़ी के लिए वापस आएँ।',
    'आपका पंजीकृत टूर्नामेंट लगभग तैयार है।',
    'टूर्नामेंट ब्रैकेट खोलें और खेलने के लिए तैयार हो जाएँ।',
  ],
  'ta': [
    'நாளை தொடங்குகிறது',
    '1 மணி நேரத்தில் தொடங்குகிறது',
    '10 நிமிடங்களில் தொடங்குகிறது',
    'உங்கள் தயாரிப்பைச் சரிபார்த்து உங்கள் இணைப்புக்குத் திரும்புங்கள்.',
    'நீங்கள் பதிவு செய்த போட்டி கிட்டத்தட்ட தயாராக உள்ளது.',
    'போட்டி அட்டவணையைத் திறந்து விளையாடத் தயாராகுங்கள்.',
  ],
  'kn': [
    'ನಾಳೆ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ',
    '1 ಗಂಟೆಯಲ್ಲಿ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ',
    '10 ನಿಮಿಷಗಳಲ್ಲಿ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ',
    'ನಿಮ್ಮ ಸಿದ್ಧತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ ನಿಮ್ಮ ಜೋಡಿಗಾಗಿ ಹಿಂತಿರುಗಿ.',
    'ನೀವು ನೋಂದಾಯಿಸಿದ ಪಂದ್ಯಾವಳಿ ಬಹುತೇಕ ಸಿದ್ಧವಾಗಿದೆ.',
    'ಪಂದ್ಯಾವಳಿ ಬ್ರಾಕೆಟ್ ತೆರೆಯಿರಿ ಮತ್ತು ಆಡಲು ಸಿದ್ಧರಾಗಿ.',
  ],
  'ml': [
    'നാളെ ആരംഭിക്കും',
    '1 മണിക്കൂറിൽ ആരംഭിക്കും',
    '10 മിനിറ്റിൽ ആരംഭിക്കും',
    'നിങ്ങളുടെ തയ്യാറെടുപ്പ് പരിശോധിച്ച് ജോടിക്കായി മടങ്ങിവരൂ.',
    'നിങ്ങൾ രജിസ്റ്റർ ചെയ്ത ടൂർണമെന്റ് ഏകദേശം തയ്യാറായി.',
    'ടൂർണമെന്റ് ബ്രാക്കറ്റ് തുറന്ന് കളിക്കാൻ തയ്യാറാകൂ.',
  ],
  'mr': [
    'उद्या सुरू होईल',
    '1 तासात सुरू होईल',
    '10 मिनिटांत सुरू होईल',
    'तुमच्या तयारीचा आढावा घ्या आणि जोडीसाठी परत या.',
    'तुमची नोंदणीकृत स्पर्धा जवळजवळ तयार आहे.',
    'स्पर्धेचे ब्रॅकेट उघडा आणि खेळण्यासाठी तयार व्हा.',
  ],
  'bn': [
    'আগামীকাল শুরু হবে',
    '১ ঘণ্টার মধ্যে শুরু হবে',
    '১০ মিনিটের মধ্যে শুরু হবে',
    'আপনার প্রস্তুতি পর্যালোচনা করুন এবং জুটির জন্য ফিরে আসুন।',
    'আপনার নিবন্ধিত টুর্নামেন্ট প্রায় প্রস্তুত।',
    'টুর্নামেন্ট ব্র্যাকেট খুলুন এবং খেলার জন্য প্রস্তুত হন।',
  ],
  'gu': [
    'આવતીકાલે શરૂ થશે',
    '1 કલાકમાં શરૂ થશે',
    '10 મિનિટમાં શરૂ થશે',
    'તમારી તૈયારી તપાસો અને તમારી જોડી માટે પાછા આવો.',
    'તમારી નોંધાયેલ ટૂર્નામેન્ટ લગભગ તૈયાર છે.',
    'ટૂર્નામેન્ટ બ્રેકેટ ખોલો અને રમવા તૈયાર થાઓ.',
  ],
  'pa': [
    'ਕੱਲ੍ਹ ਸ਼ੁਰੂ ਹੋਵੇਗਾ',
    '1 ਘੰਟੇ ਵਿੱਚ ਸ਼ੁਰੂ ਹੋਵੇਗਾ',
    '10 ਮਿੰਟਾਂ ਵਿੱਚ ਸ਼ੁਰੂ ਹੋਵੇਗਾ',
    'ਆਪਣੀ ਤਿਆਰੀ ਦੀ ਸਮੀਖਿਆ ਕਰੋ ਅਤੇ ਜੋੜੀ ਲਈ ਵਾਪਸ ਆਓ।',
    'ਤੁਹਾਡਾ ਰਜਿਸਟਰ ਕੀਤਾ ਟੂਰਨਾਮੈਂਟ ਲਗਭਗ ਤਿਆਰ ਹੈ।',
    'ਟੂਰਨਾਮੈਂਟ ਬ੍ਰੈਕਟ ਖੋਲ੍ਹੋ ਅਤੇ ਖੇਡਣ ਲਈ ਤਿਆਰ ਹੋਵੋ।',
  ],
  'ur': [
    'کل شروع ہوگا',
    '1 گھنٹے میں شروع ہوگا',
    '10 منٹ میں شروع ہوگا',
    'اپنی تیاری کا جائزہ لیں اور اپنی جوڑی کے لیے واپس آئیں۔',
    'آپ کا رجسٹرڈ ٹورنامنٹ تقریباً تیار ہے۔',
    'ٹورنامنٹ بریکٹ کھولیں اور کھیلنے کے لیے تیار ہو جائیں۔',
  ],
  'ar': [
    'يبدأ غدًا',
    'يبدأ خلال ساعة',
    'يبدأ خلال 10 دقائق',
    'راجع استعدادك وعد لمواجهتك.',
    'بطولتك المسجّلة أوشكت على البدء.',
    'افتح جدول البطولة واستعد للعب.',
  ],
  'es': [
    'comienza mañana',
    'comienza en 1 hora',
    'comienza en 10 minutos',
    'Revisa tu preparación y vuelve para tu emparejamiento.',
    'Tu torneo registrado está casi listo.',
    'Abre el cuadro del torneo y prepárate para jugar.',
  ],
  'fr': [
    'commence demain',
    'commence dans 1 heure',
    'commence dans 10 minutes',
    'Vérifiez votre préparation et revenez pour votre appariement.',
    'Votre tournoi est presque prêt.',
    'Ouvrez le tableau du tournoi et préparez-vous à jouer.',
  ],
  'de': [
    'beginnt morgen',
    'beginnt in 1 Stunde',
    'beginnt in 10 Minuten',
    'Überprüfe deine Vorbereitung und kehre zu deiner Paarung zurück.',
    'Dein angemeldetes Turnier ist fast bereit.',
    'Öffne den Turnierbaum und mach dich spielbereit.',
  ],
  'it': [
    'inizia domani',
    'inizia tra 1 ora',
    'inizia tra 10 minuti',
    'Rivedi la tua preparazione e torna per l’abbinamento.',
    'Il torneo a cui sei iscritto è quasi pronto.',
    'Apri il tabellone del torneo e preparati a giocare.',
  ],
  'pt': [
    'começa amanhã',
    'começa em 1 hora',
    'começa em 10 minutos',
    'Reveja sua preparação e volte para o emparelhamento.',
    'Seu torneio inscrito está quase pronto.',
    'Abra a chave do torneio e prepare-se para jogar.',
  ],
  'ru': [
    'начнётся завтра',
    'начнётся через 1 час',
    'начнётся через 10 минут',
    'Проверьте подготовку и вернитесь к своей паре.',
    'Ваш зарегистрированный турнир почти готов.',
    'Откройте турнирную сетку и приготовьтесь к игре.',
  ],
  'uk': [
    'почнеться завтра',
    'почнеться через 1 годину',
    'почнеться через 10 хвилин',
    'Перевірте підготовку та поверніться до своєї пари.',
    'Ваш зареєстрований турнір майже готовий.',
    'Відкрийте турнірну сітку та підготуйтеся до гри.',
  ],
  'tr': [
    'yarın başlıyor',
    '1 saat içinde başlıyor',
    '10 dakika içinde başlıyor',
    'Hazırlığını gözden geçir ve eşleşmen için geri dön.',
    'Kayıtlı turnuvan başlamak üzere.',
    'Turnuva tablosunu aç ve oynamaya hazırlan.',
  ],
  'fa': [
    'فردا شروع می‌شود',
    'تا ۱ ساعت دیگر شروع می‌شود',
    'تا ۱۰ دقیقه دیگر شروع می‌شود',
    'آمادگی خود را مرور کنید و برای رویارویی برگردید.',
    'مسابقه ثبت‌نام‌شده شما تقریباً آماده است.',
    'جدول مسابقه را باز کنید و برای بازی آماده شوید.',
  ],
  'zh': [
    '明天开始',
    '将在 1 小时后开始',
    '将在 10 分钟后开始',
    '检查你的准备情况，并回来参加配对赛。',
    '你报名的锦标赛即将开始。',
    '打开锦标赛对阵表，准备比赛。',
  ],
  'ja': [
    '明日開始します',
    '1時間後に開始します',
    '10分後に開始します',
    '準備を確認して対戦に戻りましょう。',
    '登録したトーナメントの開始が近づいています。',
    'トーナメント表を開いて対局の準備をしましょう。',
  ],
  'ko': [
    '내일 시작합니다',
    '1시간 후 시작합니다',
    '10분 후 시작합니다',
    '준비 상태를 확인하고 대진에 참여하세요.',
    '등록한 토너먼트가 곧 시작됩니다.',
    '토너먼트 대진표를 열고 경기할 준비를 하세요.',
  ],
  'id': [
    'dimulai besok',
    'dimulai dalam 1 jam',
    'dimulai dalam 10 menit',
    'Tinjau persiapanmu dan kembali untuk pasangan pertandinganmu.',
    'Turnamen yang kamu daftarkan hampir siap.',
    'Buka bagan turnamen dan bersiaplah bermain.',
  ],
  'ms': [
    'bermula esok',
    'bermula dalam 1 jam',
    'bermula dalam 10 minit',
    'Semak persediaan anda dan kembali untuk pasangan anda.',
    'Kejohanan yang anda daftar hampir sedia.',
    'Buka carta kejohanan dan bersedia untuk bermain.',
  ],
  'th': [
    'เริ่มพรุ่งนี้',
    'เริ่มในอีก 1 ชั่วโมง',
    'เริ่มในอีก 10 นาที',
    'ตรวจสอบการเตรียมตัวและกลับมาสำหรับการจับคู่ของคุณ',
    'ทัวร์นาเมนต์ที่คุณลงทะเบียนใกล้พร้อมแล้ว',
    'เปิดสายการแข่งขันและเตรียมพร้อมเล่น',
  ],
  'vi': [
    'bắt đầu vào ngày mai',
    'bắt đầu sau 1 giờ',
    'bắt đầu sau 10 phút',
    'Xem lại sự chuẩn bị và quay lại cho cặp đấu của bạn.',
    'Giải đấu bạn đăng ký sắp sẵn sàng.',
    'Mở nhánh đấu và chuẩn bị thi đấu.',
  ],
  'pl': [
    'zaczyna się jutro',
    'zaczyna się za 1 godzinę',
    'zaczyna się za 10 minut',
    'Sprawdź przygotowanie i wróć na swoje zestawienie.',
    'Twój zapisany turniej jest prawie gotowy.',
    'Otwórz drabinkę turniejową i przygotuj się do gry.',
  ],
  'nl': [
    'begint morgen',
    'begint over 1 uur',
    'begint over 10 minuten',
    'Controleer je voorbereiding en kom terug voor je koppeling.',
    'Je geregistreerde toernooi is bijna klaar.',
    'Open het toernooischema en maak je klaar om te spelen.',
  ],
  'sv': [
    'börjar i morgon',
    'börjar om 1 timme',
    'börjar om 10 minuter',
    'Kontrollera dina förberedelser och återvänd till din lottning.',
    'Din registrerade turnering är nästan redo.',
    'Öppna turneringsträdet och gör dig redo att spela.',
  ],
  'el': [
    'ξεκινά αύριο',
    'ξεκινά σε 1 ώρα',
    'ξεκινά σε 10 λεπτά',
    'Ελέγξτε την προετοιμασία σας και επιστρέψτε για το ζευγάρωμά σας.',
    'Το τουρνουά στο οποίο εγγραφήκατε είναι σχεδόν έτοιμο.',
    'Ανοίξτε το ταμπλό του τουρνουά και ετοιμαστείτε να παίξετε.',
  ],
  'he': [
    'מתחיל מחר',
    'מתחיל בעוד שעה',
    'מתחיל בעוד 10 דקות',
    'בדקו את ההכנה וחזרו לציוות שלכם.',
    'הטורניר שאליו נרשמתם כמעט מוכן.',
    'פתחו את טבלת הטורניר והתכוננו לשחק.',
  ],
  'sw': [
    'inaanza kesho',
    'inaanza baada ya saa 1',
    'inaanza baada ya dakika 10',
    'Kagua maandalizi yako na urudi kwa upangaji wako.',
    'Mashindano uliyojiandikisha yako karibu kuanza.',
    'Fungua jedwali la mashindano na uwe tayari kucheza.',
  ],
};

({String title, String body}) localizeTournamentReminder({
  required String languageCode,
  required String tournamentName,
  required int reminderIndex,
}) {
  final String code = AppLanguageController.resolveCode(languageCode);
  final List<String> values = _copy[code] ?? _copy['en']!;
  assert(reminderIndex >= 0 && reminderIndex < 3);
  return (
    title: '$tournamentName ${values[reminderIndex]}',
    body: values[reminderIndex + 3],
  );
}
