import '../features/tutorial/domain/academy_lesson.dart';
import 'academy_story_translations_europe.dart';
import 'academy_story_translations_global.dart';
import 'academy_story_translations_indic.dart';
import 'app_language.dart';

/// Fully bundled Academy copy. Nothing is sent to a translation service.
class AcademyStoryLocalizations {
  AcademyStoryLocalizations(String code)
    : code = AppLanguageController.resolveCode(code);

  final String code;

  static const Map<String, Map<String, String>> _translations =
      <String, Map<String, String>>{
        ...academyStoryIndicTranslations,
        ...academyStoryEuropeTranslations,
        ...academyStoryGlobalTranslations,
      };

  Map<String, String>? get _copy => _translations[code];

  String storyChapter(AcademyLesson lesson) =>
      _copy?['${lesson.id}.chapter'] ?? lesson.storyChapter;

  String storyNarration(AcademyLesson lesson) {
    final String value = _copy?['${lesson.id}.story'] ?? lesson.storyNarration;
    final String localized = value
        .replaceAll('{from}', lesson.from)
        .replaceAll('{to}', lesson.to)
        .replaceAll('{square}', lesson.to);
    return localized.contains(lesson.to)
        ? localized
        : '$localized ${lesson.from} → ${lesson.to}.';
  }

  static bool hasOfflineCatalog(String code) {
    final Map<String, String>? copy = _translations[code];
    return copy != null && _requiredKeys.every(copy.containsKey);
  }

  static const Set<String> _requiredKeys = <String>{
    'board.chapter',
    'board.story',
    'pawn.chapter',
    'pawn.story',
    'rook.chapter',
    'rook.story',
    'bishop.chapter',
    'bishop.story',
    'knight.chapter',
    'knight.story',
    'queen.chapter',
    'queen.story',
    'king.chapter',
    'king.story',
    'capture.chapter',
    'capture.story',
    'ui.thinkTitle',
    'ui.candidateRule',
    'ui.listen',
    'ui.pause',
    'ui.continue',
    'ui.restart',
    'ui.aiCoach',
    'ui.strapline',
    'decision.safety',
    'decision.tactics',
    'decision.endgame',
    'insight.safety',
    'insight.tactics',
    'insight.endgame',
    'feedback.wrong',
    'placement.title',
    'placement.progress',
    'placement.q1',
    'placement.q1a',
    'placement.q1b',
    'placement.q1c',
    'placement.q2',
    'placement.q2a',
    'placement.q2b',
    'placement.q2c',
    'placement.q3',
    'placement.q3a',
    'placement.q3b',
    'placement.q3c',
    'path.beginner',
    'path.intermediate',
    'metric.stars',
    'metric.mastered',
    'mission.title',
    'mission.subtitle',
    'mission.streak',
    'mission.reviewDue',
    'mission.newSkill',
    'skillMap.title',
    'skillMap.subtitle',
    'boss.title',
    'boss.noHints',
    'boss.position',
    'boss.certificate',
    'boss.retryTitle',
    'boss.passedBody',
    'boss.failedBody',
    'boss.share',
    'boss.tryAgain',
    'boss.next',
    'boss.result',
    'boss.copied',
    'boss.locked',
    'boss.unlocked',
    'boss.earned',
    'boss.start',
    'boss.view',
    'academy.title',
    'academy.subtitle',
    'academy.sectionEyebrow',
    'academy.sectionTitle',
    'academy.sectionSubtitle',
    'blindfold.title',
    'blindfold.cardTitle',
    'blindfold.cardBody',
    'blindfold.mission',
    'blindfold.memorize',
    'blindfold.hide',
    'blindfold.score',
    'blindfold.best',
    'blindfold.streak',
    'blindfold.correct',
    'blindfold.wrong',
    'blindfold.next',
    'blindfold.finish',
    'blindfold.light',
    'blindfold.dark',
    'blindfold.colour-e4.prompt',
    'blindfold.colour-e4.explanation',
    'blindfold.knight-f3.prompt',
    'blindfold.knight-f3.explanation',
    'blindfold.memory-f3.prompt',
    'blindfold.memory-f3.explanation',
    'master.title',
    'master.cardTitle',
    'master.cardBody',
    'master.eyebrow',
    'master.intro',
    'master.pauseMeta',
    'master.positionBefore',
    'master.correct',
    'master.wrong',
    'master.complete',
    'master.side.white',
    'master.side.black',
    'master.kasparov-topalov-1999.question',
    'master.kasparov-topalov-1999.idea',
    'master.aronian-anand-2013.question',
    'master.aronian-anand-2013.idea',
    'master.carlsen-nepomniachtchi-2021.question',
    'master.carlsen-nepomniachtchi-2021.idea',
    'missions.title',
    'missions.retry',
    'missions.heroTitle',
    'missions.heroBody',
    'missions.daily',
    'missions.weekly',
    'missions.claimed',
    'missions.claiming',
    'missions.claim',
    'missions.inProgress',
    'missions.coinsAdded',
    'missions.resets',
    'mission.DAILY_PLAY.title',
    'mission.DAILY_PLAY.description',
    'mission.DAILY_WIN.title',
    'mission.DAILY_WIN.description',
    'mission.WEEKLY_GAMES.title',
    'mission.WEEKLY_GAMES.description',
    'mission.WEEKLY_WINS.title',
    'mission.WEEKLY_WINS.description',
    'mission.WEEKLY_TOURNAMENT.title',
    'mission.WEEKLY_TOURNAMENT.description',
    'hero.eyebrow',
    'hero.title',
    'hero.compact',
    'hero.expanded',
    'hero.continue',
    'method.watch',
    'method.watchBody',
    'method.practice',
    'method.practiceBody',
    'method.master',
    'method.masterBody',
    'course.pieces',
    'course.piecesBody',
    'course.safety',
    'course.safetyBody',
    'course.tactics',
    'course.tacticsBody',
    'course.endgames',
    'course.endgamesBody',
    'course.lockMessage',
    'course.locked',
    'course.progress',
    'course.start',
    'course.continue',
    'coachResponse.title',
    'coachResponse.body',
    'quality.great',
    'quality.good',
    'quality.average',
    'quality.bad',
    'path.title',
    'path.next',
    'path.start',
    'path.pieces',
    'path.reasonReview',
    'path.reasonIntermediate',
    'path.reasonBeginner',
    'report.title',
    'report.empty',
    'report.summary',
    'weakness.opening',
    'weakness.kingSafety',
    'weakness.hangingPieces',
    'weakness.missedCaptures',
    'weakness.timeManagement',
    'weakness.endgame',
    'weakness.tactics',
    'weakness.calculation',
    'piece.pawn',
    'piece.rook',
    'piece.bishop',
    'piece.knight',
    'piece.queen',
    'piece.king',
    'piece.learn',
    'reason.opening',
    'reason.kingSafety',
    'reason.hangingPieces',
    'reason.missedCaptures',
    'reason.timeManagement',
    'reason.endgame',
    'reason.tactics',
    'reason.calculation',
    'check.chapter',
    'check.story',
    'escape.chapter',
    'escape.story',
    'castle.chapter',
    'castle.story',
    'knight-fork.chapter',
    'knight-fork.story',
    'back-rank.chapter',
    'back-rank.story',
    'promotion.chapter',
    'promotion.story',
    'queen-mate.chapter',
    'queen-mate.story',
    'ladder-mate.chapter',
    'ladder-mate.story',
    'en-passant.chapter',
    'en-passant.story',
    'pin.chapter',
    'pin.story',
    'skewer.chapter',
    'skewer.story',
    'discovered-attack.chapter',
    'discovered-attack.story',
    'mate-one.chapter',
    'mate-one.story',
    'opposition.chapter',
    'opposition.story',
    'rook-king-mate.chapter',
    'rook-king-mate.story',
    'stalemate.chapter',
    'stalemate.story',
    'deflection.chapter',
    'deflection.story',
    'decoy.chapter',
    'decoy.story',
    'mate-two.chapter',
    'mate-two.story',
    'smothered-mate.chapter',
    'smothered-mate.story',
    'bishop-knight-mate.chapter',
    'bishop-knight-mate.story',
    'king-shelter.chapter',
    'king-shelter.story',
    'hanging-piece.chapter',
    'hanging-piece.story',
    'double-attack.chapter',
    'double-attack.story',
    'remove-defender.chapter',
    'remove-defender.story',
    'king-pawn-basics.chapter',
    'king-pawn-basics.story',
    'rook-ending.chapter',
    'rook-ending.story',
    'course.openings',
    'course.openingsBody',
    'course.middlegame',
    'course.middlegameBody',
    'course.time',
    'course.timeBody',
    'opening-centre.chapter',
    'opening-centre.story',
    'opening-develop.chapter',
    'opening-develop.story',
    'opening-tempo.chapter',
    'opening-tempo.story',
    'opening-castle.chapter',
    'opening-castle.story',
    'opening-rooks.chapter',
    'opening-rooks.story',
    'opening-checklist.chapter',
    'opening-checklist.story',
    'opening-italian.chapter',
    'opening-italian.story',
    'opening-ruy-lopez.chapter',
    'opening-ruy-lopez.story',
    'opening-sicilian.chapter',
    'opening-sicilian.story',
    'opening-queens-gambit.chapter',
    'opening-queens-gambit.story',
    'opening-caro-kann.chapter',
    'opening-caro-kann.story',
    'opening-punish-queen.chapter',
    'opening-punish-queen.story',
    'plan-worst-piece.chapter',
    'plan-worst-piece.story',
    'plan-open-file.chapter',
    'plan-open-file.story',
    'plan-weak-square.chapter',
    'plan-weak-square.story',
    'plan-pawn-break.chapter',
    'plan-pawn-break.story',
    'plan-prophylaxis.chapter',
    'plan-prophylaxis.story',
    'plan-three-step.chapter',
    'plan-three-step.story',
    'clock-budget.chapter',
    'clock-budget.story',
    'clock-forcing-scan.chapter',
    'clock-forcing-scan.story',
    'clock-increment.chapter',
    'clock-increment.story',
    'clock-safe-premove.chapter',
    'clock-safe-premove.story',
  };

  String text(String key, {Map<String, String> values = const {}}) {
    String result = _copy?[key] ?? _english[key] ?? key;
    for (final MapEntry<String, String> entry in values.entries) {
      result = result.replaceAll('{${entry.key}}', entry.value);
    }
    return result;
  }

  String decisionQuestion(AcademyStage stage) => text(switch (stage) {
    AcademyStage.safety => 'decision.safety',
    AcademyStage.tactics => 'decision.tactics',
    AcademyStage.endgame => 'decision.endgame',
    AcademyStage.foundation => 'decision.foundation',
  });

  String decisionInsight(AcademyLesson lesson) => text(
    switch (lesson.stage) {
      AcademyStage.safety => 'insight.safety',
      AcademyStage.tactics => 'insight.tactics',
      AcademyStage.endgame => 'insight.endgame',
      AcademyStage.foundation => 'insight.foundation',
    },
    values: <String, String>{'to': lesson.to},
  );

  static const Map<String, String> _english = <String, String>{
    'blindfold.title': 'BLINDFOLD LAB',
    'blindfold.cardTitle': 'BLINDFOLD & VISUALIZATION LAB',
    'blindfold.cardBody': 'Build board vision with square colours, knight paths, and memory positions.',
    'blindfold.mission': 'MISSION {current}/{total}',
    'blindfold.memorize': 'Memorize the position…',
    'blindfold.hide': 'I AM READY · HIDE PIECES',
    'blindfold.score': 'SCORE {score}',
    'blindfold.best': 'BEST {score}',
    'blindfold.streak': '🔥 {days} DAY STREAK',
    'blindfold.correct': 'VISUALIZED!',
    'blindfold.wrong': 'REBUILD IT',
    'blindfold.next': 'NEXT MISSION',
    'blindfold.finish': 'FINISH · {score}/{total}',
    'blindfold.light': 'Light',
    'blindfold.dark': 'Dark',
    'blindfold.colour-e4.prompt':
        'Without looking at pieces: what colour is e4?',
    'blindfold.colour-e4.explanation': 'a1 is dark and colours alternate. e4 has an odd file-plus-rank total, so it is light.',
    'blindfold.knight-f3.prompt':
        'Picture a knight on f3. Which square can it reach?',
    'blindfold.knight-f3.explanation': 'A knight changes one file and two ranks, or two files and one rank. f3 to e5 is a legal L-jump.',
    'blindfold.memory-f3.prompt':
        'After the pieces disappear, where was the white knight?',
    'blindfold.memory-f3.explanation': 'The knight was developed on f3, in front of the king-side starting position.',
    'master.title': 'MASTER GAMES',
    'master.cardTitle': 'MASTER GAMES BREAKDOWN',
    'master.cardBody':
        'Pause at real turning points and discover how champions think.',
    'master.eyebrow': 'ENTER THE MASTER’S MIND',
    'master.intro': 'The game pauses at a real turning point. Calculate first, choose a move, then reveal the master’s idea.',
    'master.pauseMeta': 'PAUSE AT MOVE {move} · {side} TO MOVE',
    'master.positionBefore': 'Position before move {move}',
    'master.correct': 'MASTER MOVE FOUND',
    'master.wrong': 'CALCULATE ONE MOVE DEEPER',
    'master.complete': 'COMPLETE MASTERCLASS',
    'master.side.white': 'White',
    'master.side.black': 'Black',
    'master.kasparov-topalov-1999.question': 'Kasparov sensed the black king was exposed. Which move begins the immortal attack?',
    'master.kasparov-topalov-1999.idea': 'The rook sacrifice tears open the king. Calculation matters more than material: every reply keeps Black under forcing threats.',
    'master.aronian-anand-2013.question': 'Anand can strike before White finishes development. Which pawn break unlocks the attack?',
    'master.aronian-anand-2013.idea': 'The c-pawn sacrifice opens lines while White’s king and pieces are uncoordinated. It is a positional trigger backed by concrete tactics.',
    'master.carlsen-nepomniachtchi-2021.question': 'After hours of play, Carlsen found one precise exchange. Which move keeps the winning pressure?',
    'master.carlsen-nepomniachtchi-2021.idea': 'The rook captures with check and forces a favourable simplification. Endurance still needs accuracy: remove counterplay before collecting pawns.',
    'missions.title': 'MISSIONS',
    'missions.retry': 'RETRY',
    'missions.heroTitle': 'YOUR NEXT CHALLENGE',
    'missions.heroBody': 'Fair virtual rewards for verified play. Rewards cannot be purchased or withdrawn.',
    'missions.daily': 'DAILY MISSIONS',
    'missions.weekly': 'WEEKLY MISSIONS',
    'missions.claimed': 'CLAIMED',
    'missions.claiming': 'CLAIMING…',
    'missions.claim': 'CLAIM REWARD',
    'missions.inProgress': 'IN PROGRESS',
    'missions.coinsAdded': '{coins} coins added to your wallet.',
    'missions.resets': 'Resets in {time}',
    'mission.DAILY_PLAY.title': 'Make your move',
    'mission.DAILY_PLAY.description': 'Complete one verified online game.',
    'mission.DAILY_WIN.title': 'Winning focus',
    'mission.DAILY_WIN.description': 'Win one verified online game.',
    'mission.WEEKLY_GAMES.title': 'Weekly competitor',
    'mission.WEEKLY_GAMES.description': 'Complete five verified online games.',
    'mission.WEEKLY_WINS.title': 'Strong week',
    'mission.WEEKLY_WINS.description': 'Win three verified online games.',
    'mission.WEEKLY_TOURNAMENT.title': 'Circuit player',
    'mission.WEEKLY_TOURNAMENT.description': 'Complete one tournament pairing.',
    'ui.thinkTitle': 'THINK BEFORE THE DEMO',
    'ui.candidateRule':
        'Coach rule: compare at least three candidates before committing.',
    'ui.listen': 'LISTEN TO STORY',
    'ui.pause': 'PAUSE STORY',
    'ui.continue': 'CONTINUE STORY',
    'ui.restart': 'Start narration again',
    'ui.aiCoach': 'AI COACH',
    'ui.strapline': 'WATCH • UNDERSTAND • PRACTICE',
    'decision.foundation': 'Which destination completes the mission?',
    'decision.safety':
        'Before the coach moves: which square best protects the king?',
    'decision.tactics': 'Before the coach moves: which candidate creates the strongest forcing idea?',
    'decision.endgame': 'Before the coach moves: which candidate follows the key endgame principle?',
    'insight.foundation': '{to} completes the mission.',
    'insight.safety': '{to} is safest because it answers the immediate danger before making a new threat.',
    'insight.tactics': '{to} is strongest. Scan checks, captures, and threats first; forcing moves reduce the opponent’s choices.',
    'insight.endgame': '{to} follows the essential endgame principle. Activity and precise king or pawn placement matter more than speed.',
    'feedback.wrong': '{square} looks possible, but it misses the position’s priority. Check the opponent’s reply and compare again.',
    'placement.title': 'FIND YOUR STARTING LEVEL',
    'placement.progress': 'Question {current} of {total}',
    'placement.q1': 'A knight on g1 can jump directly to which square?',
    'placement.q1a': 'g3',
    'placement.q1b': 'f3',
    'placement.q1c': 'e2',
    'placement.q2': 'Your king is in check. What must your next move do?',
    'placement.q2a': 'Attack the queen',
    'placement.q2b': 'Create a threat',
    'placement.q2c': 'End the check',
    'placement.q3': 'Before choosing a tactic, what should you scan first?',
    'placement.q3a': 'Checks, captures, threats',
    'placement.q3b': 'Only pawn moves',
    'placement.q3c': 'The clock',
    'path.beginner': 'BEGINNER PATH',
    'path.intermediate': 'INTERMEDIATE PATH',
    'metric.stars': '{count} stars',
    'metric.mastered': '{count} mastered',
    'mission.title': 'TODAY\'S MEMORY WORKOUT',
    'mission.subtitle': 'Three short lessons selected for lasting recall',
    'mission.streak': '{count} day streak',
    'mission.reviewDue': 'Review due · strengthen this memory',
    'mission.newSkill': 'New skill · continue your learning path',
    'skillMap.title': 'YOUR CHESSVERSE SKILL MAP',
    'skillMap.subtitle':
        'Master the path from first move to confident finisher',
    'boss.title': '{course} · MASTERY CHALLENGE',
    'boss.noHints': 'No hints · Trust your calculation',
    'boss.position': 'POSITION {current} OF {total}',
    'boss.certificate': 'MASTERY CERTIFICATE',
    'boss.retryTitle': 'ONE MORE TRAINING RUN',
    'boss.passedBody':
        'ChessVerseAI certifies your {course} mastery. Score: {score}.',
    'boss.failedBody': 'You scored {score}. Review the patterns and earn at least 2 correct answers.',
    'boss.share': 'COPY SHARE MESSAGE',
    'boss.tryAgain': 'TRY CHALLENGE AGAIN',
    'boss.next': 'NEXT POSITION',
    'boss.result': 'SEE RESULT',
    'boss.copied': 'Achievement copied',
    'boss.locked': 'Complete every lesson to unlock the course boss.',
    'boss.unlocked': 'Solve 3 no-hint positions and score at least 2.',
    'boss.earned': 'MASTERY CERTIFICATE EARNED',
    'boss.start': 'START',
    'boss.view': 'VIEW',
    'academy.title': 'LEARN CHESS',
    'academy.subtitle': 'Build skills one lesson at a time',
    'academy.sectionEyebrow': 'CHESS ACADEMY',
    'academy.sectionTitle': 'Your lessons, in order',
    'academy.sectionSubtitle': 'Start with every piece, then learn king safety, tactics and checkmate.',
    'hero.eyebrow': 'AI-GUIDED TRAINING',
    'hero.title': 'ChessVerseAI Coach',
    'hero.compact': 'Learn from every important move.',
    'hero.expanded':
        'Understand every important move with clear, practical coaching.',
    'hero.continue': 'CONTINUE LEARNING',
    'method.watch': 'WATCH',
    'method.watchBody': 'AI shows the move',
    'method.practice': 'PRACTICE',
    'method.practiceBody': 'You repeat it',
    'method.master': 'MASTER',
    'method.masterBody': 'AI corrects you',
    'course.pieces': 'Piece Basics',
    'course.piecesBody': 'Learn how every piece moves and captures.',
    'course.safety': 'King Safety',
    'course.safetyBody': 'Understand check, escape squares, and pins.',
    'course.tactics': 'Tactics',
    'course.tacticsBody': 'Forks, skewers, discovered attacks, and mates.',
    'course.endgames': 'Endgames',
    'course.endgamesBody': 'Finish cleanly with rook, queen, and pawn endings.',
    'course.openings': 'Opening Principles',
    'course.openingsBody':
        'Build a strong position before launching an attack.',
    'course.middlegame': 'Middlegame Planning',
    'course.middlegameBody':
        'Turn positional clues into a clear practical plan.',
    'course.time': 'Time Management',
    'course.timeBody':
        'Think clearly, use increment, and play safe moves under pressure.',
    'course.lockMessage':
        'Complete the previous academy stage to unlock this course.',
    'course.locked': 'LOCKED • Finish the previous stage',
    'course.progress': '{done} of {total} lessons',
    'course.start': 'START LESSON',
    'course.continue': 'CONTINUE',
    'coachResponse.title': 'HOW THE AI COACH RESPONDS',
    'coachResponse.body': 'Every key move receives a clear quality label and a short improvement idea.',
    'quality.great': 'Great',
    'quality.good': 'Good',
    'quality.average': 'Average',
    'quality.bad': 'Bad',
    'path.title': 'YOUR AI LEARNING PATH',
    'path.next': 'Next: {lesson}',
    'path.start': 'Start recommended lesson',
    'path.pieces': 'LEARN EVERY PIECE',
    'path.reasonReview': 'Memory refresh due today. A short replay now keeps this pattern available in your next game.',
    'path.reasonIntermediate': 'Your placement shows solid piece knowledge. Start with king safety, then unlock tactical calculation.',
    'path.reasonBeginner': 'Start with piece movement, then the AI coach will adapt your path after every reviewed game.',
    'report.title': 'WEEKLY AI IMPROVEMENT REPORT',
    'report.empty': 'Complete a game to activate your personal skill map.',
    'report.summary': '{count} recent games reviewed • strongest: {strongest} • focus: {focus}',
    'weakness.opening': 'Opening',
    'weakness.kingSafety': 'King safety',
    'weakness.hangingPieces': 'Piece safety',
    'weakness.missedCaptures': 'Capture scan',
    'weakness.timeManagement': 'Time management',
    'weakness.endgame': 'Endgame',
    'weakness.tactics': 'Tactical vision',
    'weakness.calculation': 'Calculation',
    'piece.pawn': 'Pawn',
    'piece.rook': 'Rook',
    'piece.bishop': 'Bishop',
    'piece.knight': 'Knight',
    'piece.queen': 'Queen',
    'piece.king': 'King',
    'piece.learn': 'Learn {piece}',
    'reason.opening': 'Your recent games became difficult early. Build the centre, develop once, and castle before attacking.',
    'reason.kingSafety': 'Your king often stayed in the centre. This 5-minute lesson trains safe castling decisions.',
    'reason.hangingPieces': 'Material swings decided recent games. Train a safety scan before every move.',
    'reason.missedCaptures': 'You are leaving tactical opportunities on the board. Scan checks, captures, and threats in order.',
    'reason.timeManagement': 'Time pressure affected your results. Learn a short candidate-move routine for faster decisions.',
    'reason.endgame': 'Your longest games need a cleaner finish. Activate the king and learn pawn promotion technique.',
    'reason.tactics': 'Engine-reviewed mistakes show missed tactical resources. Train forcing checks, captures, forks, and pins.',
    'reason.calculation': 'Your positions need a more consistent candidate-move check. Compare two forcing lines before committing.',
  };
}
