package com.epitomehub.chessverse.academy;

import com.epitomehub.chessverse.auth.PlayerAuthenticationService;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.time.LocalDate;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

@RestController @RequestMapping("/api/v1/academy") @Transactional
public class AcademyOperationsController {
    private final JdbcTemplate db; private final PlayerAuthenticationService auth;
    public AcademyOperationsController(JdbcTemplate db,PlayerAuthenticationService auth){this.db=db;this.auth=auth;}
    public record Announcement(@Pattern(regexp="ALL|COACH|STUDENT|PARENT") String audience,@NotBlank @Size(max=150) String title,@NotBlank @Size(max=2000) String message,LocalDate expiresOn){}
    public record Attendance(@NotNull UUID studentId,@NotNull LocalDate classDate,@Pattern(regexp="PRESENT|ABSENT|LATE|EXCUSED") String status,@Size(max=500) String note){}
    public record Preferences(boolean announcements,boolean assignments,boolean reports,boolean billing,boolean emailEnabled){}
    public record Subscription(@Pattern(regexp="UPGRADE|DOWNGRADE|CANCEL") String action,@Pattern(regexp="STARTER|GROWTH|SCHOOL") String planCode,@Min(1) Integer seats,@NotNull LocalDate effectiveOn){}
    public record ReportSchedule(UUID studentId,@Pattern(regexp="WEEKLY|MONTHLY") String period,boolean emailEnabled,@NotNull LocalDate nextRunOn){}
    private record Access(UUID account,UUID member,String role){boolean admin(){return "ORGANIZATION_ADMIN".equals(role);}boolean trainer(){return admin()||"COACH".equals(role);}}

    @GetMapping("/{org}/announcements") public List<Map<String,Object>> announcements(@RequestHeader("Authorization")String bearer,@PathVariable UUID org){Access a=access(bearer,org);return rows("SELECT * FROM academy_announcement WHERE organization_id=? AND (expires_at IS NULL OR expires_at>CURRENT_TIMESTAMP) AND (audience='ALL' OR audience=?) ORDER BY created_at DESC",org,a.role);}
    @PostMapping("/{org}/announcements") public Map<String,Object> announce(@RequestHeader("Authorization")String bearer,@PathVariable UUID org,@Valid @RequestBody Announcement i){Access a=access(bearer,org);require(a.trainer(),HttpStatus.FORBIDDEN,"Coach or administrator required.");UUID id=UUID.randomUUID();db.update("INSERT INTO academy_announcement(id,organization_id,created_by,audience,title,message,expires_at) VALUES(?,?,?,?,?,?,?)",id,org,a.member,i.audience,i.title.trim(),i.message.trim(),i.expiresOn);audit(org,a,"ANNOUNCEMENT_CREATED","ANNOUNCEMENT",id.toString(),i.audience);return Map.of("id",id);}
    @DeleteMapping("/{org}/announcements/{id}") public void deleteAnnouncement(@RequestHeader("Authorization")String bearer,@PathVariable UUID org,@PathVariable UUID id){Access a=access(bearer,org);require(a.admin(),HttpStatus.FORBIDDEN,"Organization Admin required.");require(db.update("DELETE FROM academy_announcement WHERE organization_id=? AND id=?",org,id)==1,HttpStatus.NOT_FOUND,"Announcement not found.");audit(org,a,"ANNOUNCEMENT_DELETED","ANNOUNCEMENT",id.toString(),null);}

    @GetMapping("/{org}/attendance") public List<Map<String,Object>> attendance(@RequestHeader("Authorization")String bearer,@PathVariable UUID org,@RequestParam LocalDate from,@RequestParam LocalDate to){Access a=access(bearer,org);require(!to.isBefore(from)&&!from.isBefore(LocalDate.now().minusYears(2))&&!to.isAfter(LocalDate.now()),HttpStatus.BAD_REQUEST,"Invalid attendance range.");String scope=a.admin()?"":" AND EXISTS (SELECT 1 FROM academy_student s WHERE s.organization_id=t.organization_id AND s.id=t.student_id AND (s.coach_id=? OR s.account_id=? OR EXISTS (SELECT 1 FROM academy_parent_link p WHERE p.organization_id=s.organization_id AND p.student_id=s.id AND p.member_id=?)))";return a.admin()?rows("SELECT t.* FROM academy_attendance t WHERE organization_id=? AND class_date BETWEEN ? AND ? ORDER BY class_date DESC",org,from,to):rows("SELECT t.* FROM academy_attendance t WHERE organization_id=? AND class_date BETWEEN ? AND ?"+scope+" ORDER BY class_date DESC",org,from,to,a.member,a.account,a.member);}
    @PutMapping("/{org}/attendance") public void attendance(@RequestHeader("Authorization")String bearer,@PathVariable UUID org,@Valid @RequestBody Attendance i){Access a=access(bearer,org);require(a.trainer(),HttpStatus.FORBIDDEN,"Coach or administrator required.");require(a.admin()||count("SELECT COUNT(*) FROM academy_student WHERE organization_id=? AND id=? AND coach_id=?",org,i.studentId,a.member)==1,HttpStatus.FORBIDDEN,"Student is outside your scope.");int changed=db.update("UPDATE academy_attendance SET status=?,recorded_by=?,note=?,updated_at=CURRENT_TIMESTAMP WHERE organization_id=? AND student_id=? AND class_date=?",i.status,a.member,i.note,org,i.studentId,i.classDate);if(changed==0)db.update("INSERT INTO academy_attendance(organization_id,student_id,class_date,status,recorded_by,note) VALUES(?,?,?,?,?,?)",org,i.studentId,i.classDate,i.status,a.member,i.note);audit(org,a,"ATTENDANCE_RECORDED","STUDENT",i.studentId.toString(),i.status);}

    @GetMapping("/{org}/trial-reminder") public Map<String,Object> trialReminder(@RequestHeader("Authorization")String bearer,@PathVariable UUID org) {
        Access a=access(bearer,org);
        if(!a.trainer())return Map.of("show",false);
        var trials=rows("SELECT e.trial_started_on,o.renewal_date FROM academy_enrollment e JOIN academy_organization o ON o.id=e.organization_id WHERE o.id=? AND o.plan='Free trial' AND o.status='ACTIVE'",org);
        if(trials.isEmpty()||trials.getFirst().get("trial_started_on")==null||trials.getFirst().get("renewal_date")==null)return Map.of("show",false);
        LocalDate started=LocalDate.parse(trials.getFirst().get("trial_started_on").toString()),ends=LocalDate.parse(trials.getFirst().get("renewal_date").toString()),now=LocalDate.now();
        if(now.isBefore(started.plusDays(6))||!now.equals(ends.minusDays(1)))return Map.of("show",false);
        if(count("SELECT COUNT(*) FROM academy_notification_preference WHERE organization_id=? AND member_id=? AND billing=FALSE",org,a.member)>0)return Map.of("show",false);
        String scope=a.admin()?"":" AND s.coach_id=?";
        String sql="SELECT COALESCE(SUM(v.blunders),0) AS blunders,COALESCE(SUM(v.retry_attempts),0) AS attempts,COALESCE(SUM(v.retry_attempts-v.retry_failures),0) AS solved FROM academy_observation v JOIN academy_student s ON s.id=v.student_id AND s.organization_id=v.organization_id WHERE v.organization_id=? AND v.practiced_on>=? AND v.practiced_on<=?"+scope;
        var totals=rows(sql,a.admin()?new Object[]{org,started,now}:new Object[]{org,started,now,a.member}).getFirst();
        long blunders=((Number)totals.get("blunders")).longValue(),attempts=((Number)totals.get("attempts")).longValue(),solved=((Number)totals.get("solved")).longValue();
        String evidence=blunders>0||attempts>0?"During your trial, coach-recorded sessions for your students show "+blunders+" blunders and "+solved+" successful position retries out of "+attempts+" attempts. ":"Your academy workspace is ready for your students and training plans. ";
        return Map.of("show",true,"title","Your free trial ends tomorrow","message",evidence+"Your free trial ends on "+ends+". "+(a.admin()?"Choose a monthly or yearly plan to continue using your academy workspace.":"Ask your academy admin to choose a monthly or yearly plan to continue."),"endsOn",ends,"blunders",blunders,"retryAttempts",attempts,"retrySolved",solved,"canChoosePlan",a.admin());
    }

    @GetMapping("/{org}/preferences") public Map<String,Object> preferences(@RequestHeader("Authorization")String bearer,@PathVariable UUID org){Access a=access(bearer,org);var r=rows("SELECT * FROM academy_notification_preference WHERE organization_id=? AND member_id=?",org,a.member);if(r.isEmpty())return Map.of("announcements",true,"assignments",true,"reports",true,"billing",true,"email_enabled",true);return r.getFirst();}
    @PutMapping("/{org}/preferences") public void preferences(@RequestHeader("Authorization")String bearer,@PathVariable UUID org,@RequestBody Preferences i){Access a=access(bearer,org);int changed=db.update("UPDATE academy_notification_preference SET announcements=?,assignments=?,reports=?,billing=?,email_enabled=? WHERE organization_id=? AND member_id=?",i.announcements,i.assignments,i.reports,i.billing,i.emailEnabled,org,a.member);if(changed==0)db.update("INSERT INTO academy_notification_preference(organization_id,member_id,announcements,assignments,reports,billing,email_enabled) VALUES(?,?,?,?,?,?,?)",org,a.member,i.announcements,i.assignments,i.reports,i.billing,i.emailEnabled);}

    @GetMapping("/{org}/audit") public List<Map<String,Object>> audit(@RequestHeader("Authorization")String bearer,@PathVariable UUID org){Access a=access(bearer,org);require(a.admin(),HttpStatus.FORBIDDEN,"Organization Admin required.");return rows("SELECT event_type,target_type,target_id,details,created_at FROM academy_audit_event WHERE organization_id=? ORDER BY created_at DESC LIMIT 500",org);}
    @DeleteMapping("/{org}/members/{id}") public void deactivate(@RequestHeader("Authorization")String bearer,@PathVariable UUID org,@PathVariable UUID id){Access a=access(bearer,org);require(a.admin(),HttpStatus.FORBIDDEN,"Organization Admin required.");require(!a.member.equals(id),HttpStatus.CONFLICT,"You cannot deactivate your own administrator membership.");require(count("SELECT COUNT(*) FROM academy_student WHERE organization_id=? AND coach_id=?",org,id)+count("SELECT COUNT(*) FROM academy_batch WHERE organization_id=? AND coach_id=?",org,id)==0,HttpStatus.CONFLICT,"Reassign this coach's students and batches first.");require(db.update("UPDATE academy_member SET active=FALSE WHERE organization_id=? AND id=? AND active=TRUE",org,id)==1,HttpStatus.NOT_FOUND,"Active member not found.");audit(org,a,"MEMBER_DEACTIVATED","MEMBER",id.toString(),null);}

    @GetMapping("/{org}/subscription-requests") public List<Map<String,Object>> subscriptions(@RequestHeader("Authorization")String bearer,@PathVariable UUID org){Access a=access(bearer,org);require(a.admin(),HttpStatus.FORBIDDEN,"Organization Admin required.");return rows("SELECT * FROM academy_subscription_request WHERE organization_id=? ORDER BY created_at DESC",org);}
    @PostMapping("/{org}/subscription-requests") public Map<String,Object> subscription(@RequestHeader("Authorization")String bearer,@PathVariable UUID org,@Valid @RequestBody Subscription i){Access a=access(bearer,org);require(a.admin(),HttpStatus.FORBIDDEN,"Organization Admin required.");require(!i.effectiveOn.isBefore(LocalDate.now()),HttpStatus.BAD_REQUEST,"Effective date cannot be in the past.");if("DOWNGRADE".equals(i.action))require(i.seats!=null&&i.seats>=count("SELECT COUNT(*) FROM academy_student WHERE organization_id=? AND active=TRUE",org),HttpStatus.CONFLICT,"Downgrade seats must cover active students.");UUID id=UUID.randomUUID();db.update("INSERT INTO academy_subscription_request(id,organization_id,requested_by,action,plan_code,seats,effective_on) VALUES(?,?,?,?,?,?,?)",id,org,a.member,i.action,i.planCode,i.seats,i.effectiveOn);audit(org,a,"SUBSCRIPTION_REQUESTED","SUBSCRIPTION",id.toString(),i.action);return Map.of("id",id,"paymentRequired",false);}
    @PostMapping("/{org}/report-schedules") public Map<String,Object> schedule(@RequestHeader("Authorization")String bearer,@PathVariable UUID org,@Valid @RequestBody ReportSchedule i){Access a=access(bearer,org);require(a.trainer(),HttpStatus.FORBIDDEN,"Coach or administrator required.");if(i.studentId!=null)require(count("SELECT COUNT(*) FROM academy_student WHERE organization_id=? AND id=?",org,i.studentId)==1,HttpStatus.BAD_REQUEST,"Student not found.");UUID id=UUID.randomUUID();db.update("INSERT INTO academy_report_schedule(id,organization_id,created_by,student_id,period,email_enabled,next_run_on) VALUES(?,?,?,?,?,?,?)",id,org,a.member,i.studentId,i.period,i.emailEnabled,i.nextRunOn);audit(org,a,"REPORT_SCHEDULED","REPORT_SCHEDULE",id.toString(),i.period);return Map.of("id",id);}
    @GetMapping("/{org}/report-schedules") public List<Map<String,Object>> schedules(@RequestHeader("Authorization")String bearer,@PathVariable UUID org){Access a=access(bearer,org);require(a.trainer(),HttpStatus.FORBIDDEN,"Coach or administrator required.");return a.admin()?rows("SELECT * FROM academy_report_schedule WHERE organization_id=? ORDER BY created_at DESC",org):rows("SELECT * FROM academy_report_schedule WHERE organization_id=? AND created_by=? ORDER BY created_at DESC",org,a.member);}

    private Access access(String bearer,UUID org){UUID account=auth.requireBearer(bearer).id();var r=rows("SELECT m.id,m.role,o.status,o.renewal_date FROM academy_member m JOIN academy_organization o ON o.id=m.organization_id WHERE m.organization_id=? AND m.account_id=? AND m.active=TRUE",org,account);require(!r.isEmpty(),HttpStatus.FORBIDDEN,"Active academy membership required.");require(!"SUSPENDED".equals(r.getFirst().get("status")),HttpStatus.FORBIDDEN,"Academy is suspended.");require(r.getFirst().get("renewal_date")==null||LocalDate.parse(r.getFirst().get("renewal_date").toString()).isAfter(LocalDate.now()),HttpStatus.PAYMENT_REQUIRED,"Your trial or plan has ended. Choose a plan to continue.");return new Access(account,UUID.fromString(r.getFirst().get("id").toString()),r.getFirst().get("role").toString());}
    private void audit(UUID org,Access a,String event,String type,String target,String details){db.update("INSERT INTO academy_audit_event(id,organization_id,actor_account_id,event_type,target_type,target_id,details) VALUES(?,?,?,?,?,?,?)",UUID.randomUUID(),org,a.account,event,type,target,details);}
    private long count(String sql,Object...args){return db.queryForObject(sql,Long.class,args);}private void require(boolean ok,HttpStatus s,String m){if(!ok)throw new ResponseStatusException(s,m);}private List<Map<String,Object>> rows(String sql,Object...args){return db.query(sql,(rs,n)->{Map<String,Object> r=new LinkedHashMap<>();for(int x=1;x<=rs.getMetaData().getColumnCount();x++)r.put(rs.getMetaData().getColumnLabel(x).toLowerCase(Locale.ROOT),rs.getObject(x));return r;},args);}
}
