spring:
  config:
    import: optional:file:../.env[.properties]
  datasource:
    url: jdbc:h2:file:./data/chessverse-local;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true

server:
  address: 127.0.0.1

management:
  health:
    mail:
      enabled: false

chessverse:
  engine:
    stockfish-path: ../.local/stockfish/stockfish.exe
  auth:
    sms:
      mode: console
      expose-development-code: true
